
MACRO (MXA_SOURCE_PROPERTIES NAME HEADERS SOURCES)

INSTALL (FILES ${HEADERS}
            DESTINATION include/MXADataModel/${NAME}
            COMPONENT Headers           
)

source_group(src\\Base FILES ${HEADERS} ${SOURCES})

set_property(SOURCE ${HEADERS}
 PROPERTY MACOSX_PACKAGE_LOCATION Headers/${NAME}
)

ENDMACRO (MXA_SOURCE_PROPERTIES NAME HEADERS SOURCES)
