


#MESSAGE (STATUS "[${MODULE_NAME}] MXADATAMODEL_BUILDING: '${MXADATAMODEL_BUILDING}'")
IF (NOT DEFINED MXADATAMODEL_BUILDING OR NOT MXADATAMODEL_BUILDING)
    SET (MXA_USE_HDF5 ON)
    SET (MXA_USE_XML  OFF)
    SET (MXA_USE_TIFF OFF)
    SET (BUILD_EXAMPLES FALSE)
    SET (BUILD_TESTING FALSE)
    SET (MXA_EXTERNAL_HDF5_LIBRARY ${HDF_LIBRARY})
    SET (MXADATAMODEL_LIB_NAME MXADataModel)
    SET (MXA_USE_DEBUG_LIBRARY_NAME FALSE)
    MESSAGE (STATUS "Plugin: [${MODULE_NAME}] adding MXADataModel Library")
    ADD_SUBDIRECTORY("${MXA_SOURCE_DIR}" MXADataModel)
    SET(PARAVIEW_ADDITIONAL_LIBRARIES ${PARAVIEW_ADDITIONAL_LIBRARIES} ${MXADATAMODEL_LIB_NAME} )
    SET (MXADATAMODEL_BUILDING TRUE )
    #-------------------------------------------------------------------------------
    #  Find Boost so we can get the Include Directories
    SET (Boost_FIND_REQUIRED TRUE)
    SET (Boost_FIND_QUIETLY TRUE)
    SET (Boost_USE_FILESYSTEM TRUE)
    SET (Boost_USE_SYSTEM TRUE)
    INCLUDE (${MXA_SOURCE_DIR}/Resources/CMake/MXAFindBoost.cmake)
    INCLUDE_DIRECTORIES(${Boost_INCLUDE_DIRS})  # Include the Boost Headers
    LINK_DIRECTORIES(${Boost_LIBRARY_DIRS})
    #- Add the required Libraries for MXA to function
    SET (PARAVIEW_ADDITIONAL_LIBRARIES 
        ${PARAVIEW_ADDITIONAL_LIBRARIES} 
        ${Boost_FILESYSTEM_LIBRARY}
        ${Boost_SYSTEM_LIBRARY}
        ${HDF_LIBRARY}
    )
ENDIF (NOT DEFINED MXADATAMODEL_BUILDING OR NOT MXADATAMODEL_BUILDING)

INCLUDE_DIRECTORIES (${MXA_SOURCE_DIR}/src)
INCLUDE_DIRECTORIES (${ParaView_BINARY_DIR}/MXADataModel)

