

# ------ Add support for HDF5
SET(MXA_USE_HDF5 ON)
SET(MXA_EXTERNAL_HDF5_LIBRARY ${PARAVIEW_HDF5_LIBRARIES})
SET(HDF5_FOUND 1)
SET(HDF5_LIBRARIES ${PARAVIEW_HDF5_LIBRARIES})
INCLUDE_DIRECTORIES( ${HDF5_INCLUDE_DIR} )
#SET(HDF5_INCLUDE_DIRS "${ParaView_SOURCE_DIR}/Utilities/hdf5" ${ParaView_BINARY_DIR}/Utilities/hdf5)

# ------- Add support for Expat and XML parsing
SET (MXA_USE_XML  ON)
SET (MXA_EXTERNAL_EXPAT_LIBRARY vtkexpat)
SET (EXPAT_FOUND 1)
SET (EXPAT_LIBRARIES vtkexpat)
SET (EXPAT_INCLUDE_DIRS "${ParaView_SOURCE_DIR}/VTK/Utilities/vtkexpat")

# ---- Add support for Tiff image functionality
SET (MXA_USE_TIFF OFF)
#SET (MXA_EXTERNAL_TIFF_LIBRARY vtktiff)
#SET (TIFF_FOUND 1)
#SET (TIFF_LIBRARIES vtktiff)
#SET (TIFF_INCLUDE_DIRS  ${ParaView_SOURCE_DIR}/VTK/Utilities/vtktiff
#                        ${ParaView_BINARY_DIR}/VTK/Utilities/vtktiff )


SET (MXA_BUILD_EXAMPLES OFF CACHE BOOL "" )
SET (MXA_BUILD_TESTING FALSE)

SET (MXADATAMODEL_LIB_NAME MXADataModel)
SET (MXA_USE_DEBUG_LIBRARY_NAME FALSE)
set (MXA_BOOST_HEADERS_ONLY TRUE)

set (MXA_IGNORE_INSTALL_RULES ON CACHE BOOL "Ignore the MXA Install Rules, defaulting to the enclosing projects install rules")
set (MXA_BUILD_TESTING_SAVE ${MXA_BUILD_TESTING})
#SET (MXA_BUILD_TESTING ON)
SET (MXA_OUTPUT_DIRS_DEFINED 1)
set (MXA_BOOST_HEADERS_ONLY 0)
ADD_SUBDIRECTORY("${MXADataModel_SOURCE_DIR}" ${ParaView_BINARY_DIR}/${MXADATAMODEL_LIB_NAME})
INCLUDE_DIRECTORIES(${Boost_INCLUDE_DIRS})  # Include the Boost Headers
SET (MXA_BUILD_TESTING ${MXA_BUILD_TESTING_SAVE})
SET (MXADATAMODEL_TARGET_ADDED TRUE )


SET (MXADATAMODEL_TARGET_ADDED "1" CACHE INTERNAL "MXADataModel Added to ParaView as a libary")
MESSAGE (STATUS "[${MODULE_NAME}] Added the MXADataModel library.")

INCLUDE_DIRECTORIES (${MXADataModel_SOURCE_DIR}/Source)
INCLUDE_DIRECTORIES (${ParaView_BINARY_DIR}/MXADataModel)

